### ISSUE TITLE
a suggestion or improvement 

### ISSUE THREAD

**Issue by SophiaLi20** [CityOfBoston/access-boston-config#294]
In the [src/configs/prod/apps.yaml](https://github.com/CityOfBoston/access-boston-config/blob/master/src/configs/prod/apps.yaml) we can add comments in different places for Improved Readability, Simplified Maintenance that helps in reducing the effort needed to debug or update the configuration as requirements evolve and Faster Onboarding so that new team members can quickly understand the purpose of the YAML file and how it is structured.

Example for this in code ;-

```
`# Notice section for employees to go paperless and verify mailing addresses
notice:
  label: 'City Employees - Go Paperless'  # Label for the notice
  pretext: ''
  text: 'Click the ESS tile to confirm that your mailing address is correct & to go paperless for your W2, ACA and paystubs. Tax documents will be available in January.'
```

```
# Applications section - Lists available apps grouped by categories
categories:
  - title: Applications  # Main category title
    show_request_access_link: false  # Hides request access link for this category
    icons: true  # Enables icons for apps in this category
    apps:
      - title: Beacon
        url: https://beacon.boston.gov/cob  # URL for the Beacon app
        icon: https://assets.boston.gov/icons/accessboston/lighthouse_basic_icon.svg  # Icon for Beacon app

      - title: Employee Self-Service
        url: https://ess.boston.gov/  # Link to the ESS portal
        icon: https://assets.boston.gov/icons/accessboston/ess.svg
        groups:
          - SG_AB_ESS  # Group with access to this app
```
